package org.xxpay.shop.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xxpay.shop.dao.model.GoodsOrder;
import org.xxpay.shop.dao.model.GoodsOrderExample;

public interface GoodsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int countByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int deleteByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int deleteByPrimaryKey(String goodsOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int insert(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int insertSelective(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    List<GoodsOrder> selectByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    GoodsOrder selectByPrimaryKey(String goodsOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsOrder record, @Param("example") GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByExample(@Param("record") GoodsOrder record, @Param("example") GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByPrimaryKey(GoodsOrder record);
}