package org.xxpay.shop.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.xxpay.shop.dao.model.SelfPickup;
import org.xxpay.shop.dao.model.SelfPickupExample;

public interface SelfPickupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int countByExample(SelfPickupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int deleteByExample(SelfPickupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int insert(SelfPickup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int insertSelective(SelfPickup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    List<SelfPickup> selectByExample(SelfPickupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByExampleSelective(@Param("record") SelfPickup record, @Param("example") SelfPickupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    int updateByExample(@Param("record") SelfPickup record, @Param("example") SelfPickupExample example);
}