package org.xxpay.shop.dao.model;

import java.util.Date;

public class GoodsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String goodsOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.GoodsName
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Amount
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.UserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.Status
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.PayOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.ChannelId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.ChannelUserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private String channelUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.CreateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_order.UpdateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsOrderId
     *
     * @return the value of t_goods_order.GoodsOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getGoodsOrderId() {
        return goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsOrderId
     *
     * @param goodsOrderId the value for t_goods_order.GoodsOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setGoodsOrderId(String goodsOrderId) {
        this.goodsOrderId = goodsOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsId
     *
     * @return the value of t_goods_order.GoodsId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsId
     *
     * @param goodsId the value for t_goods_order.GoodsId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.GoodsName
     *
     * @return the value of t_goods_order.GoodsName
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.GoodsName
     *
     * @param goodsName the value for t_goods_order.GoodsName
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Amount
     *
     * @return the value of t_goods_order.Amount
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Amount
     *
     * @param amount the value for t_goods_order.Amount
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.UserId
     *
     * @return the value of t_goods_order.UserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.UserId
     *
     * @param userId the value for t_goods_order.UserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.Status
     *
     * @return the value of t_goods_order.Status
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.Status
     *
     * @param status the value for t_goods_order.Status
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.PayOrderId
     *
     * @return the value of t_goods_order.PayOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.PayOrderId
     *
     * @param payOrderId the value for t_goods_order.PayOrderId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.ChannelId
     *
     * @return the value of t_goods_order.ChannelId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.ChannelId
     *
     * @param channelId the value for t_goods_order.ChannelId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.ChannelUserId
     *
     * @return the value of t_goods_order.ChannelUserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public String getChannelUserId() {
        return channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.ChannelUserId
     *
     * @param channelUserId the value for t_goods_order.ChannelUserId
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setChannelUserId(String channelUserId) {
        this.channelUserId = channelUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.CreateTime
     *
     * @return the value of t_goods_order.CreateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.CreateTime
     *
     * @param createTime the value for t_goods_order.CreateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_order.UpdateTime
     *
     * @return the value of t_goods_order.UpdateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_order.UpdateTime
     *
     * @param updateTime the value for t_goods_order.UpdateTime
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_order
     *
     * @mbggenerated Tue Mar 10 16:02:45 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsOrderId=").append(goodsOrderId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", amount=").append(amount);
        sb.append(", userId=").append(userId);
        sb.append(", status=").append(status);
        sb.append(", payOrderId=").append(payOrderId);
        sb.append(", channelId=").append(channelId);
        sb.append(", channelUserId=").append(channelUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}