package org.xxpay.shop.dao.model;

public class SelfPickup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_self_pickup.AssetId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    private String assetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_self_pickup.GoodsId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_self_pickup.BuyerID
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    private String buyerID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_self_pickup.IsPickUp
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    private String isPickUp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_self_pickup.AssetId
     *
     * @return the value of t_self_pickup.AssetId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public String getAssetId() {
        return assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_self_pickup.AssetId
     *
     * @param assetId the value for t_self_pickup.AssetId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_self_pickup.GoodsId
     *
     * @return the value of t_self_pickup.GoodsId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_self_pickup.GoodsId
     *
     * @param goodsId the value for t_self_pickup.GoodsId
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_self_pickup.BuyerID
     *
     * @return the value of t_self_pickup.BuyerID
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public String getBuyerID() {
        return buyerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_self_pickup.BuyerID
     *
     * @param buyerID the value for t_self_pickup.BuyerID
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public void setBuyerID(String buyerID) {
        this.buyerID = buyerID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_self_pickup.IsPickUp
     *
     * @return the value of t_self_pickup.IsPickUp
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public String getIsPickUp() {
        return isPickUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_self_pickup.IsPickUp
     *
     * @param isPickUp the value for t_self_pickup.IsPickUp
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    public void setIsPickUp(String isPickUp) {
        this.isPickUp = isPickUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_self_pickup
     *
     * @mbggenerated Mon Mar 16 15:39:25 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", assetId=").append(assetId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", buyerID=").append(buyerID);
        sb.append(", isPickUp=").append(isPickUp);
        sb.append("]");
        return sb.toString();
    }
}